export const VIEW_POST_REQUEST = "VIEW_POST_REQUEST";
export const VIEW_POST_SUCCESS = "VIEW_POST_SUCCESS";
export const VIEW_POST_FAIL = "VIEW_POST_FAIL";
export const VIEW_POST_RESET = "VIEW_POST_RESET";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";
export const LIKE_POST_RESET = "LIKE_POST_RESET";

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAIL = "UNLIKE_POST_FAIL";
export const UNLIKE_POST_RESET = "UNLIKE_POST_RESET";

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL";
export const COMMENT_POST_RESET = "COMMENT_POST_RESET";

export const SHARE_POST_REQUEST = "SHARE_POST_REQUEST";
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS";
export const SHARE_POST_FAIL = "SHARE_POST_FAIL";
export const SHARE_POST_RESET = "SHARE_POST_RESET";

export const ADD_DIAMOND_INTO_POST_REQUEST = "ADD_DIAMOND_INTO_POST_REQUEST";
export const ADD_DIAMOND_INTO_POST_SUCCESS = "ADD_DIAMOND_INTO_POST_SUCCESS";
export const ADD_DIAMOND_INTO_POST_FAIL = "ADD_DIAMOND_INTO_POST_FAIL";
export const ADD_DIAMOND_INTO_POST_RESET = "ADD_DIAMOND_INTO_POST_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

