export const BADGES_REQUEST = "BADGES_REQUEST";
export const BADGES_SUCCESS = "BADGES_SUCCESS";
export const BADGES_FAIL = "BADGES_FAIL";
export const BADGES_RESET = "BADGES_RESET";

export const CREATE_BADGE_REQUEST = "CREATE_BADGE_REQUEST";
export const CREATE_BADGE_SUCCESS = "CREATE_BADGE_SUCCESS";
export const CREATE_BADGE_FAIL = "CREATE_BADGE_FAIL";
export const CREATE_BADGE_RESET = "CREATE_BADGE_RESET";

export const DELETE_BADGE_REQUEST = "DELETE_BADGE_REQUEST";
export const DELETE_BADGE_SUCCESS = "DELETE_BADGE_SUCCESS";
export const DELETE_BADGE_FAIL = "DELETE_BADGE_FAIL";
export const DELETE_BADGE_RESET = "DELETE_BADGE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

