export const PAGES_REQUEST = "PAGES_REQUEST";
export const PAGES_SUCCESS = "PAGES_SUCCESS";
export const PAGES_FAIL = "PAGES_FAIL";
export const PAGES_RESET = "PAGES_RESET";

export const CREATE_PAGE_REQUEST = "CREATE_PAGE_REQUEST";
export const CREATE_PAGE_SUCCESS = "CREATE_PAGE_SUCCESS";
export const CREATE_PAGE_FAIL = "CREATE_PAGE_FAIL";
export const CREATE_PAGE_RESET = "CREATE_PAGE_RESET";

export const SINGLE_PAGE_REQUEST = "SINGLE_PAGE_REQUEST";
export const SINGLE_PAGE_SUCCESS = "SINGLE_PAGE_SUCCESS";
export const SINGLE_PAGE_FAIL = "SINGLE_PAGE_FAIL";
export const SINGLE_PAGE_RESET = "SINGLE_PAGE_RESET";

export const UPDATE_PAGE_REQUEST = "UPDATE_PAGE_REQUEST";
export const UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
export const UPDATE_PAGE_FAIL = "UPDATE_PAGE_FAIL";
export const UPDATE_PAGE_RESET = "UPDATE_PAGE_RESET";

export const DELETE_PAGE_REQUEST = "DELETE_PAGE_REQUEST";
export const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS";
export const DELETE_PAGE_FAIL = "DELETE_PAGE_FAIL";
export const DELETE_PAGE_RESET = "DELETE_PAGE_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

