export const SUPPORTS_REQUEST = "SUPPORTS_REQUEST";
export const SUPPORTS_SUCCESS = "SUPPORTS_SUCCESS";
export const SUPPORTS_FAIL = "SUPPORTS_FAIL";
export const SUPPORTS_RESET = "SUPPORTS_RESET";


export const DELETE_SUPPORT_REQUEST = "DELETE_SUPPORT_REQUEST";
export const DELETE_SUPPORT_SUCCESS = "DELETE_SUPPORT_SUCCESS";
export const DELETE_SUPPORT_FAIL = "DELETE_SUPPORT_FAIL";
export const DELETE_SUPPORT_RESET = "DELETE_SUPPORT_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

